### ISSUE TITLE
Unable to connect to localhost:7687

### ISSUE THREAD

**Issue by samasalam** [utnaf/neo4j-connector-apache-spark-notebooks#7]
Hello 
When I run the following:
```
%neo4j
import org.apache.spark.sql.{SaveMode, SparkSession}

val spark = SparkSession.builder().getOrCreate()

spark.read.format("org.neo4j.spark.DataSource")
  .option("url", "bolt://localhost:7687")
  .option("labels", "Person")
  .load()
  .show()
```

The following error occur:
Unable to connect to localhost:7687, ensure the database is running and that there is a working network connection to it.
What should I do ?

**Comment by utnaf** [comment]
Hi there! If you are using this Zeppelin Docker setup with the provided Neo4j Docker instance you should do this

```python
spark.read.format("org.neo4j.spark.DataSource")
  .option("url", "bolt://neo4j:7687") # use neo4j not localhost
  .option("labels", "Person")
  .option("authentication.type", "basic") # the provided Neo4j instance has authentication setup with neo4j / password credentials
  .option("authentication.basic.username", "neo4j")
  .option("authentication.basic.password", "password")
  .load()
  .show()
```

**Comment by samasalam** [comment]
> d Neo4j Docker instance you should do this



> Hi there! If you are using this Zeppelin Docker setup with the provided Neo4j Docker instance you should do this
> 
> ```python
> spark.read.format("org.neo4j.spark.DataSource")
>   .option("url", "bolt://neo4j:7687") # use neo4j not localhost
>   .option("labels", "Person")
>   .option("authentication.type", "basic") # the provided Neo4j instance has authentication setup with neo4j / password credentials
>   .option("authentication.basic.username", "neo4j")
>   .option("authentication.basic.password", "password")
>   .load()
>   .show()
> ```

I tried the code you wrote. the following error occur:
`The client is unauthorized due to authentication failure.`

what should I do? btw, do I need to setup a standalone neo4j? I already installed it and I added a user with neo4j/password and the same error occur.

**Comment by utnaf** [comment]
I'm sorry are you using the zeppelin notebooks?

**Comment by utnaf** [comment]
I literally just ran that code on the master branch and it's working just fine.

![Screenshot 2021-05-25 at 16 53 23](https://user-images.githubusercontent.com/1318539/119519483-bf1d6800-bd79-11eb-86ba-f0659b36d90d.png)

**Comment by samasalam** [comment]
> I'm sorry are you using the zeppelin notebooks?

yes.

**Comment by samasalam** [comment]
> docker-compose ps

C:\Users\Sama\Downloads\neo4j-connector-apache-spark-notebooks-master>docker-compose ps

```
                          Name                                        Command                State     Ports
------------------------------------------------------------------------------------------------------------
neo4j-connector-apache-spark-notebooks-master_neo4j_1      /sbin/tini -g -- /docker-e ...   Exit 0
neo4j-connector-apache-spark-notebooks-master_zeppelin_1   /usr/bin/tini -- bin/zeppe ...   Exit 143
```

**Comment by utnaf** [comment]
Well none of the container are is working. Pretty much that's why is not working.

Make sure you don't have any other service running on ports 8080, 7474 and 7687.

Then, just to be sure, run

```
docker-compose down
docker-compose rm
docker-compose up --force-recreate
```

And try again.

**Comment by samasalam** [comment]
I run it before then close it to run what you typed : docker-compose ps

**Comment by utnaf** [comment]
Oh... you should have run it on another tab, that command makes sense only if run when the container are running.

Run

```
docker-compose down
docker-compose rm
docker-compose up --force-recreate
```

And try again please. This is a Docker issue, everything is working on my side.

**Comment by samasalam** [comment]
> docker-compose ps

 ```
                Name                               Command               State                   Ports
------------------------------------------------------------------------------------------------------------------------
neo4j-connector-apache-spark-            /sbin/tini -g -- /docker-e ...   Up      7473/tcp, 0.0.0.0:7474->7474/tcp,:::74
notebooks-master_neo4j_1                                                          74->7474/tcp, 0.0.0.0:7687->7687/tcp,:
                                                                                  ::7687->7687/tcp
neo4j-connector-apache-spark-            /usr/bin/tini -- bin/zeppe ...   Up      0.0.0.0:8080->8080/tcp,:::8080->8080/t
notebooks-master_zeppelin_1                                                       cp

```

**Comment by utnaf** [comment]
Mmm try using `zeppelin` instead of `password` in the password option

**Comment by samasalam** [comment]
> Mmm try using `zeppelin` instead of `password` in the password option

I updated the pw in the neo4j interpreter. the code run but the table is empty. Below is the output
+----+--------+
|<id>|<labels>|
+----+--------+
+----+--------+

**Comment by utnaf** [comment]
Yeah of course, the database is empty by default, you need to add some data yourself or you can follow the instructions in the neo4j browser by typing `:play movie-graph`.

I suggest you to use just the provided neo4j instance if you're new to this.

**Comment by samasalam** [comment]
Thanks for your great help.
Well I want to connect to a db that I already created it in the neo4j Desktop. where I can find guide for that? 
BTW I run the :play movie-graph. The table fulled with data but no graph is presented.

**Comment by utnaf** [comment]
You just need to adjust the url, username and password to match your neo4j instance. 

The neo4j connector doesn't present the graph, just the table. You can read more here https://neo4j.com/developer/apache-spark/

**Comment by samasalam** [comment]
> You just need to adjust the url, username and password to match your neo4j instance.
> 
> The neo4j connector doesn't present the graph, just the table. You can read more here https://neo4j.com/developer/apache-spark/

what do you mean by neo4j instance? the one that is already installed (neo4j desktop)?

**Comment by utnaf** [comment]
Yes, exactly
